baseurl = "http://code.rosborough.ca/"
languageCode = "en-us"
title = "Dave Rosborough"
theme = "hyde"

[params]
  description = "Ruby on Rails, jQuery, Objective-C, and other tips and tricks."
  copyright = "Copyright © 2015 Dave Rosborough.  All Rights Reserved."